version: "3.7"

services:
    frontend:
        build:
            context: .
            dockerfile: _docker/Dockerfile
        ports:
            - "8181:80"
        volumes:
            - .:/var/www
        container_name: frontend_nginx

